#!/usr/bin/env bash
# Update package lists
sudo apt-get update

# Install Nginx if not already installed
sudo apt-get install -y nginx

# Create a simple index.html file
echo "Hello World!" > index.html
sudo mv index.html /var/www/html

# Create a custom 404 error page
echo "Ceci n'est pas une page" > 404.html
sudo mv 404.html /var/www/html

# Create the Nginx configuration file with the custom settings
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOL
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    # Add the custom header
    add_header X-Served-By \$hostname;
}
EOL

# Restart Nginx to apply the new configuration
sudo service nginx restart
